services:
  mongodb:
    image: mongo:7
    healthcheck:
      test: ['CMD-SHELL', 'mongosh --quiet --eval "db.adminCommand({ ping: 1 })" || exit 1']
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - mongodb_data_integration:/data/db
    networks:
      - bedrock_network

volumes:
  mongodb_data_integration:

networks:
  bedrock_network:
    driver: bridge
